#!/usr/bin/env bash
#
# Read an upload log (e.g. document-log-prod.txt) and emit aws s3 mv commands to
# rename objects whose keys contain literal double-quote characters from CSV export.
#
# Parses lines like:
#   UPLOAD line 3: /path/to/file.pdf -> s3://bucket/prefix/"uuid"
#   FOLDER line 2: /docs/... -> s3://bucket/prefix/"2006-2007"/
#
# Usage:
#   ./scripts/fix-quoted-s3-keys-from-log.sh ~/document-log-prod.txt
#   ./scripts/fix-quoted-s3-keys-from-log.sh ~/document-log-prod.txt --output ~/fix-s3-keys.sh
#   ./scripts/fix-quoted-s3-keys-from-log.sh ~/document-log-prod.txt --dry-run
#   ./scripts/fix-quoted-s3-keys-from-log.sh ~/document-log-prod.txt --execute
#
set -o pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="${ENV_FILE:-$REPO_ROOT/.env.local}"

load_env_file() {
  if [[ ! -f "$ENV_FILE" ]]; then
    return 0
  fi
  set -a
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  set +a
}

usage() {
  sed -n '2,16p' "$0"
}

LOG_FILE=""
OUTPUT_FILE=""
DRY_RUN=false
EXECUTE=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    -h|--help)
      usage
      exit 0
      ;;
    --output|-o)
      OUTPUT_FILE="$2"
      shift 2
      ;;
    --dry-run)
      DRY_RUN=true
      shift
      ;;
    --execute)
      EXECUTE=true
      shift
      ;;
    -*)
      echo "Unknown option: $1" >&2
      exit 1
      ;;
    *)
      if [[ -z "$LOG_FILE" ]]; then
        LOG_FILE="$1"
      else
        echo "Unexpected argument: $1" >&2
        exit 1
      fi
      shift
      ;;
  esac
done

LOG_FILE="${LOG_FILE:-$HOME/document-log-prod.txt}"

if [[ ! -f "$LOG_FILE" ]]; then
  echo "ERROR: log file not found: $LOG_FILE" >&2
  exit 1
fi

if $EXECUTE && $DRY_RUN; then
  echo "ERROR: use either --dry-run or --execute, not both" >&2
  exit 1
fi

load_env_file

AWS_DEFAULT_REGION="${AWS_DEFAULT_REGION:-${AWS_S3_REGION:-ap-southeast-2}}"
export AWS_DEFAULT_REGION

strip_quotes() {
  local s="$1"
  s="${s//\"/}"
  echo "$s"
}

# Collect s3://bucket/key from UPLOAD / FOLDER lines (dedupe, keep keys with ")
KEYS_FILE="$(mktemp)"
SORTED_KEYS_FILE="$(mktemp)"
trap 'rm -f "$KEYS_FILE" "$SORTED_KEYS_FILE"' EXIT
BUCKET=""

: > "$KEYS_FILE"

while IFS= read -r line; do
  [[ "$line" == *" -> s3://"* ]] || continue
  uri="${line#* -> }"
  uri="${uri%%$'\r'}"
  [[ "$uri" == s3://* ]] || continue

  rest="${uri#s3://}"
  current_bucket="${rest%%/*}"
  key="${rest#*/}"

  if [[ -z "$BUCKET" ]]; then
    BUCKET="$current_bucket"
  elif [[ "$current_bucket" != "$BUCKET" ]]; then
    echo "ERROR: multiple buckets in log ($BUCKET vs $current_bucket)" >&2
    exit 1
  fi

  [[ "$key" == *\"* ]] || continue
  printf '%s\n' "$key"
done < "$LOG_FILE" > "$KEYS_FILE.raw"

sort -u "$KEYS_FILE.raw" > "$KEYS_FILE"
rm -f "$KEYS_FILE.raw"

KEY_COUNT=$(wc -l < "$KEYS_FILE" | tr -d ' ')
if [[ "$KEY_COUNT" -eq 0 ]]; then
  echo "No S3 keys containing double quotes found in $LOG_FILE"
  exit 0
fi

awk '{ print length "|" $0 }' "$KEYS_FILE" | sort -t'|' -k1,1nr | cut -d'|' -f2- > "$SORTED_KEYS_FILE"

if [[ -z "$OUTPUT_FILE" && ! $DRY_RUN && ! $EXECUTE ]]; then
  OUTPUT_FILE="$HOME/fix-quoted-s3-keys-${BUCKET}.sh"
fi

emit_commands() {
  local key new_key old_uri new_uri
  echo "#!/usr/bin/env bash"
  echo "# Generated by fix-quoted-s3-keys-from-log.sh from: $LOG_FILE"
  echo "# Bucket: $BUCKET"
  echo "# Commands: $KEY_COUNT"
  echo "# Review before running. Renames remove literal \\\" characters from object keys."
  echo "set -o pipefail"
  echo "AWS_DEFAULT_REGION=\"${AWS_DEFAULT_REGION}\""
  echo "export AWS_DEFAULT_REGION"
  echo ""
  echo "moved=0"
  echo "failed=0"
  echo ""

  while IFS= read -r key; do
    [[ -z "$key" ]] && continue
    new_key="$(strip_quotes "$key")"
    if [[ "$key" == "$new_key" ]]; then
      continue
    fi
    old_uri="s3://${BUCKET}/${key}"
    new_uri="s3://${BUCKET}/${new_key}"
    cat <<EOF
if aws s3 ls "$(printf '%q' "$old_uri")" >/dev/null 2>&1; then
  if aws s3 mv "$(printf '%q' "$old_uri")" "$(printf '%q' "$new_uri")" --only-show-errors; then
    echo "OK  $new_key"
    moved=\$((moved + 1))
  else
    echo "FAIL $(printf '%q' "$old_uri")" >&2
    failed=\$((failed + 1))
  fi
else
  echo "SKIP (missing) $(printf '%q' "$old_uri")"
fi
EOF
  done < "$SORTED_KEYS_FILE"

  echo ""
  echo "echo \"\""
  echo "echo \"Done. moved=\$moved failed=\$failed\""
  echo "[[ \$failed -gt 0 ]] && exit 1"
  echo "exit 0"
}

if $DRY_RUN; then
  echo "# Dry run: $KEY_COUNT rename(s) for bucket s3://${BUCKET}"
  echo ""
  while IFS= read -r key; do
    [[ -z "$key" ]] && continue
    new_key="$(strip_quotes "$key")"
    printf 'aws s3 mv %q %q\n' "s3://${BUCKET}/${key}" "s3://${BUCKET}/${new_key}"
  done < "$SORTED_KEYS_FILE"
  exit 0
fi

if $EXECUTE; then
  if [[ -z "${AWS_ACCESS_KEY_ID:-}" || -z "${AWS_SECRET_ACCESS_KEY:-}" ]]; then
    echo "ERROR: AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY must be set (e.g. in $ENV_FILE)" >&2
    exit 1
  fi
  export AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY
  [[ -n "${AWS_SESSION_TOKEN:-}" ]] && export AWS_SESSION_TOKEN
  unset AWS_PROFILE

  echo "Executing $KEY_COUNT rename(s) on s3://${BUCKET} ..."
  moved=0
  failed=0
  while IFS= read -r key; do
    [[ -z "$key" ]] && continue
    new_key="$(strip_quotes "$key")"
    old_uri="s3://${BUCKET}/${key}"
    new_uri="s3://${BUCKET}/${new_key}"
    if aws s3 ls "$old_uri" >/dev/null 2>&1; then
      if aws s3 mv "$old_uri" "$new_uri" --only-show-errors; then
        echo "OK  $new_key"
        moved=$((moved + 1))
      else
        echo "FAIL $old_uri" >&2
        failed=$((failed + 1))
      fi
    else
      echo "SKIP (missing) $old_uri"
    fi
  done < "$SORTED_KEYS_FILE"
  echo ""
  echo "Done. moved=$moved failed=$failed"
  [[ $failed -gt 0 ]] && exit 1
  exit 0
fi

emit_commands > "$OUTPUT_FILE"
chmod +x "$OUTPUT_FILE"
echo "Wrote $KEY_COUNT rename command(s) to: $OUTPUT_FILE"
echo "Review, then run: $OUTPUT_FILE"
